### PR TITLE
add country tests

### PR DESCRIPTION
**Pull request by Bas-Man**
- update to upstream master
- Add additional country tests that currently fail
- (tests) Add Tests for `Country` detection

### CODE REVIEW

**Comment by IGI-111** [comment]
All the tests pass with the fix that's on the latest master. Remove everything but the tests and I'll merge this.

**Comment by Bas-Man** [comment]
Hmmm. Seems this branch is a bit odd. It should not contain a Cargo.lock as this should always have been ignored.

Let me see if I can workout what's going on.

**Comment by Bas-Man** [comment]
I am not a git expert. But I am thinking that your local git repo might be tracking `Cargo.lock` Or have an old version that was not removed after adding `Cargo.lock` to the `.gitignore`

On my system I confirmed that `Cargo.lock` is in the .gitignore file
I also issued the `git rm --cached Cargo.lock` command which returns
```sh
❯ git rm --cached Cargo.lock
fatal: pathspec 'Cargo.lock' did not match any files
```

I then checkeout your version
```sh
❯ git remote -v
origin	git@github.com:Bas-Man/torrent-name-parser.git (fetch)
origin	git@github.com:Bas-Man/torrent-name-parser.git (push)
upstream	git@github.com:IGI-111/torrent-name-parser.git (fetch)
upstream	git@github.com:IGI-111/torrent-name-parser.git (push)
```

Output
```sh
❯ git checkout upstream/master
Note: switching to 'upstream/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e91de4c Release 0.11.2
❯ ls
Cargo.lock Cargo.toml LICENSE    README.md  benches    examples   src        target
❯ rm Cargo.lock
❯ git rm --cached Cargo.lock
rm 'Cargo.lock'
```
These seems to indicate that your master was tracking `Cargo.lock` at some point in the past.

**Comment by IGI-111** [comment]
Fixed it, I committed the lockfile with the fix by mistake.

**Comment by Bas-Man** [comment]
Ok. will work though getting up to date with your master and up date the PR resolving any conflicts that I find.

**Comment by Bas-Man** [comment]
Are you sure that the tests pass?
This is my output
```sh
failures:

---- test::country::criminal_uk::criminal_uk stdout ----
thread 'test::country::criminal_uk::criminal_uk' panicked at 'assertion failed: `(left == right)`
  left: `"criminal"`,
 right: `"criminal uk"`', src/test.rs:621:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::country::the_last_of_us::the_last_of_us_lower stdout ----
thread 'test::country::the_last_of_us::the_last_of_us_lower' panicked at 'assertion failed: `(left == right)`
  left: `"the last of"`,
 right: `"the last of us"`', src/test.rs:602:13

---- test::country::the_last_of_us::the_last_of_us_as_titled stdout ----
thread 'test::country::the_last_of_us::the_last_of_us_as_titled' panicked at 'assertion failed: `(left == right)`
  left: `"The Last of"`,
 right: `"The Last of Us"`', src/test.rs:595:13


failures:
    test::country::criminal_uk::criminal_uk
    test::country::the_last_of_us::the_last_of_us_as_titled
    test::country::the_last_of_us::the_last_of_us_lower

test result: FAILED. 28 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.21s

```

**Comment by Bas-Man** [comment]
Hmmm. Seems my code is not accepting your pattern update :) I will need to update it manually perhaps. So this seems to be on my side.

**Pull request merged**
